kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: footballmatch-development
  name: postgres-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  selector:
    matchLabels:
      name: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  project: footballmatch
  tier: database
  environment: development
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
    project: footballmatch
    tier: database
    environment: development
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: footballmatch-development
  name: postgres
  labels:
    name: postgres
    project: footballmatch
    environment: development
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        project: footballmatch
        tier: database
        environment: development
    spec:
      containers:
        - image: "postgres:9.6.2"
          name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: postgres_password
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-data-claim
