apiVersion: v1
kind: Service
metadata:
  namespace: footballmatch-production
  name: frontend
  labels:
    name: frontend
    project: footballmatch
    environment: production
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: footballmatch
    tier: frontend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: footballmatch-production
  name: frontend
  labels:
    name: frontend
    project: footballmatch
    environment: production
spec:
  template:
    metadata:
      labels:
        app: footballmatch
        tier: frontend
    spec:
      containers:
        - image: asia.gcr.io/dprails5ondocker/footballmatch-frontend:1.0.0
          name: nginx
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]