apiVersion: v1
kind: Service
metadata:
  namespace: todos-api-production
  name: postgres
  labels:
    name: postgres
    project: todosapi
    environment: production
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: todos-api-production
  name: postgres
  labels:
    name: postgres
    project: todosapi
    environment: production
spec:
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: "postgres:9.6.2"
          name: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: todos-api-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: todos-api-config
                  key: postgres_password
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: todos-api-config
                  key: pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          gcePersistentDisk:
            fsType: ext4
            pdName: postgres-disk
