apiVersion: v1
kind: Service
metadata:
  namespace: todos-api-production
  name: nginx
  labels:
    name: nginx
    project: todos-api
    environment: production
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: todos-api
    tier: nginx
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: todos-api-production
  name: nginx
  labels:
    name: nginx
    project: todos-api
    environment: production
spec:
  template:
    metadata:
      labels:
        app: todos-api
        tier: nginx
    spec:
      containers:
        - image: asia.gcr.io/dprails5ondocker/todos-app-nginx:1.0.1
          name: nginx
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]